config/routes.rb
Rails.application.routes.draw do

  resources :cocktails, only: [:create, :index, :new, :show] do
    resources :doses, only: [:create, :new, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :ingredient_id, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

 def index
   @cocktail = Cocktail.find(params[:cocktail_id])
   @doses = @cocktail.doses
 end

 def new
   @cocktail = Cocktail.find(params[:cocktail_id])
   @dose = Dose.new
 end

 def create
   @dose = Dose.new(dose_params)
   @cocktail = Cocktail.find(params[:cocktail_id])
   @dose.cocktail = @cocktail
   if @dose.save
     redirect_to cocktail_path(@cocktail)
   else
     render :new
   end
 end

 def destroy
   @dose = Dose.find(params[:id])
   @cocktail = Cocktail.find(params[:cocktail_id])
   @dose.destroy
   redirect_to cocktail_doses_path(@cocktail)
 end

 private

 def dose_params
   params.require(:dose).permit(:description, :ingredient_id)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Our cocktails</h1>
<% @cocktails.each do |cocktail| %>
  <div><%= link_to cocktail.name, cocktail_path(cocktail) %></div>
<% end %>

<%= link_to "Add a cocktail", new_cocktail_path %>

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
 <%= f.input :name %>

 <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<% @cocktail.doses.each do |dose| %>
  <div><%= dose.description %> of <%= dose.ingredient.name %></div>
<% end %>
<%= link_to "add some doses", new_cocktail_dose_path(@cocktail) %>
<%= link_to "Back to cocktails", cocktails_path %>

app/views/doses/new.html.erb
<h1> <%= Cocktail.find(params[:cocktail_id]).name.capitalize %> </h1>

<h2>Add a dose</h2>
<%= simple_form_for [@cocktail, @dose] do |f| %>
 <%= f.input :description %>
 <%= f.association :ingredient %>
 <%= f.submit "add a dose", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%# render "components/navbar" %>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>